# Cloud Build configuration for automated CI/CD
# This file enables automatic deployment on git push

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ufe-research-writer:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ufe-research-writer:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ufe-research-writer:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ufe-research-writer:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ufe-research-writer'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ufe-research-writer:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '900'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'GOOGLE_API_KEY=${_GOOGLE_API_KEY},TAVILY_API_KEY=${_TAVILY_API_KEY},LANGUAGE=${_LANGUAGE}'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ufe-research-writer:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ufe-research-writer:latest'

# Build timeout
timeout: '1200s'

# Substitution variables (set these in Cloud Build trigger settings)
substitutions:
  _GOOGLE_API_KEY: 'your-google-api-key'
  _TAVILY_API_KEY: 'your-tavily-api-key'
  _LANGUAGE: 'mn'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
