name: ufe-research-writer
region: nyc

services:
  - name: web
    # Docker-based deployment
    dockerfile_path: Dockerfile.adk-web

    # Source code location
    github:
      repo: YOUR_GITHUB_USERNAME/finance-research-agent
      branch: main
      deploy_on_push: true

    # Environment variables
    envs:
      - key: GOOGLE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: TAVILY_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_REGION
        value: "sgp1"
        scope: RUN_TIME
      - key: SPACES_BUCKET
        value: "finance-bucket"
        scope: RUN_TIME
      - key: LANGUAGE
        value: "mn"
        scope: RUN_TIME
      - key: PORT
        value: "8080"
        scope: RUN_TIME

    # Health check
    health_check:
      http_path: /healthz
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # HTTP configuration
    http_port: 8080

    # Instance configuration
    instance_count: 1
    instance_size_slug: professional-xs  # 1GB RAM, 1 vCPU

    # Routes
    routes:
      - path: /

# Alerts (optional)
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
